ARG FROM_IMAGE

FROM ${FROM_IMAGE}

ARG USERID
ARG USERNAME

# Install rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > install-rust.sh
RUN chmod +x ./install-rust.sh
RUN ./install-rust.sh -y

RUN groupadd -g ${USERID} ${USERNAME}
RUN useradd -m -l -u ${USERID} -g ${USERNAME} ${USERNAME}
USER ${USERNAME}